### ISSUE TITLE
Pagination html generated in wrong order

### ISSUE THREAD

**Issue by stuffandthings** [patricklindsay/will_paginate-materialize#2]
The HTML generated looks like this:
`<a rel="start" href="/builds?page=1"><li class="waves-effect active">1</li></a>`

this is the incorrect order, and instead of making the square surrounding like it should it gets squashed horizontally.

Switching the others of the `<li>` and `<a>` tags fixes this:
`<li class="waves-effect active"><a rel="start" href="/builds?page=1">1</a></li>`

Was working for me earlier, I updated the Materialize CSS gem to the latest and I'm not sure if that broke it or what.

**Comment by muZk** [comment]
Same here. I used the following workaround:

``` ruby
# lib/materialize_renderer.rb
class MaterializeRenderer < MaterializePagination::Rails

  # @return [String] rendered pagination link
  def page_number(page)
    classes = ['waves-effect', ('active' if page == current_page)].join(' ')
    tag :li, link(page, page, :rel => rel_value(page)), class: classes
  end

end
```

And on the view:

``` ruby
= will_paginate @users, renderer: MaterializeRenderer
```

**Comment by eiwi1101** [comment]
Actually, given #4 includes a fix to this and others, I'd suggest using that fix/branch until the PR is accepted.
`gem 'will_paginate-materialize', github: 'harrybournis/will_paginate-materialize'`

**Comment by matiasmasca** [comment]
The harrybournis repo works fine for me and solved some rendering problems

**Comment by patricklindsay** [comment]
Ok that PR is now merged. Sorry about the delay. If someone could let me know if it's fixed and I'll release a new version.

**Comment by joshlin** [comment]
The current 0.1.2 version still does not work correctly. The harrybournis repo works for me with will pagination 3.1.6.
